source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-theme-yat"
gem "webrick", "~> 1.7"
gem "csv"
gem "base64"
gem "ostruct"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-paginate"
  gem "jekyll-spaceship"
end
